const shopActionTypes = {
    FETCHING_DATA_START: 'FETCHING_DATA_START',
    FETCHIGN_DATA_SUCCESS: 'FETCHIGN_DATA_SUCCESS',
    FETCHIGN_DATA_FAILURE: 'FETCHIGN_DATA_FAILURE',
};
export default shopActionTypes;
