const cartActionTypes = {
    TOGGLE_DROPDOWN_VISIBLITY: 'TOGGLE_DROPDOWN_VISIBLITY',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    DECREASE_ITEM: 'DECREASE_ITEM',
    CLEAR_CART: 'CLEAR_CART',
};

export default cartActionTypes;
