const cartActionTypes = {
    TOGGLE_DROPDOWN_VISIBLITY: 'TOGGLE_DROPDOWN_VISIBLITY',
    ADD_ITEM: 'ADD_ITEM',
    DECREASE_ITEM: 'REMOVE_ITEM',
    DECREASE_ITEM: 'DECREASE_ITEM',
};

export default cartActionTypes;
