const usersActionTypes = {
    SIGNIN_FAILURE: 'GOOGLE_SIGNIN_FAILURE',
    SIGNIN_SUCCUSS: 'GOOGLE_SIGNIN_SUCCUSS',

    GOOGLE_SIGNIN_START: 'GOOGLE_SIGNIN_START',

    EMAIL_SIGNIN_START: 'EMAIL_SIGNIN_START',
};

export default usersActionTypes;
