const userActionTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',

    GOOGLE_SIGNIN_START: 'GOOGLE_SIGNIN_START',
    GOOGLE_SIGNIN_SUCCUSS: 'GOOGLE_SIGNIN_SUCCUSS',
    GOOGLE_SIGNIN_FAILURE: 'GOOGLE_SIGNIN_FAILURE',

    EMAIL_SIGNIN_START: 'EMAIL_SIGNIN_START',
    EMAIL_SIGNIN_SUCCUSS: 'EMAIL_SIGNIN_SUCCUSS',
    EMAIL_SIGNIN_FAILURE: 'EMAIL_SIGNIN_FAILURE',
};

export default userActionTypes;
