const usersActionTypes = {
    SIGNIN_FAILURE: 'SIGNIN_FAILURE',
    SIGNIN_SUCCUSS: 'SIGNIN_SUCCUSS',

    SIGNIN_LOADING_START: 'SIGNIN_LOADING_START',
    SIGNIN_LOADING_STOP: 'SIGNIN_LOADING_STOP',

    SIGNOUT_START: 'SIGNOUT_START',
    SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
    SIGNOUT_FAILURE: 'SIGNOUT_FAILURE',

    GOOGLE_SIGNIN_START: 'GOOGLE_SIGNIN_START',

    EMAIL_SIGNIN_START: 'EMAIL_SIGNIN_START',

    CHECK_USER_SESSION: 'CHECK_USER_SESSION',
};

export default usersActionTypes;
